import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import Navbar from "@/components/Navbar";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-surface-950 text-slate-200 antialiased selection:bg-brand-indigo/30">
        <div className="glow-bg" />
        <Navbar />
        <main className="flex-grow relative">{children}</main>
        <footer className="bg-surface-950/50 backdrop-blur-md border-t border-white/5 py-16 mt-auto">
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <div className="grid grid-cols-1 md:grid-cols-4 gap-12 mb-12">
              <div className="col-span-1 md:col-span-2">
                <Link href="/" className="text-2xl font-black tracking-tighter text-white uppercase mb-4 block italic">
                  CLS<span className="text-brand-indigo">.</span> LUXURY
                </Link>
                <p className="text-slate-500 max-w-sm text-sm leading-relaxed font-medium">
                  Crafting a legacy of minimalist excellence. Our curated collections represent the pinnacle of modern luxury fashion.
                </p>
              </div>
              <div>
                <h4 className="text-white font-bold text-xs uppercase tracking-[0.2em] mb-6">Collections</h4>
                <ul className="space-y-3 text-slate-500 text-sm font-medium">
                  <li><Link href="/products" className="hover:text-brand-indigo transition-all duration-300">All Masterpieces</Link></li>
                  <li><Link href="/products?category=Men" className="hover:text-brand-indigo transition-all duration-300">Men's Edit</Link></li>
                  <li><Link href="/products?category=Women" className="hover:text-brand-indigo transition-all duration-300">Women's Edit</Link></li>
                </ul>
              </div>
              <div>
                <h4 className="text-white font-bold text-xs uppercase tracking-[0.2em] mb-6">Support</h4>
                <ul className="space-y-3 text-slate-500 text-sm font-medium">
                  <li><Link href="/contact" className="hover:text-brand-indigo transition-all duration-300">Contact Concierge</Link></li>
                  <li><Link href="/faq" className="hover:text-brand-indigo transition-all duration-300">Acquisition FAQ</Link></li>
                  <li><Link href="/shipping" className="hover:text-brand-indigo transition-all duration-300">Shipping Standard</Link></li>
                </ul>
              </div>
            </div>
            <div className="pt-8 border-t border-white/5 text-center text-slate-500 text-sm">
              <p>&copy; {new Date().getFullYear()} Clothing Store. Crafted for excellence.</p>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
